### PR TITLE
Skip applying polyfill in non-DOM SSR environments

### LINKED ISSUE #30: Polyfill Throws in a Server-Side Rendering (SSR) Environment
Hey @progers,

My application is currently consuming a library which relies on the pathseg polyfill (thanks so much for this polyfill btw!)

We're a React app and have a requirement to enable server-side rendering on our end. Unfortunately, importing the pathseg polyfill results in an error being thrown for `window` being undefined in the server-side environment. 

A quick one-liner can be added to make the polyfill compatible in a DOM-less SSR environment like `react-dom/server`'s. This would be placed as the first line inside the IIFE:

```ts
(function() { "use strict";
    if (typeof window === 'undefined') return;

    // ... rest of code here ...
}());
```

I can create a quick PR if needed?

Thanks!
Greg

### PR DESCRIPTION
**Pull request by gregjacobs**
Closes #30

### CODE REVIEW

**Comment by progers** [comment]
Thanks for your patch and the explanation leading up to it!

**Comment by gregjacobs** [comment]
Np! Thanks for the discussion and merging! Much appreciated!

Best,
Greg

**Comment by gregjacobs** [comment]
Oh, can you publish a new version to npm? :)

**Comment by progers** [comment]
Done! Would you mind double-checking my work?

https://github.com/progers/pathseg has been updated to 1.2.1, then I published this new version at https://www.npmjs.com/package/pathseg/v/1.2.1

**Comment by gregjacobs** [comment]
Looks good! Thanks so much!

Best,
Greg

**Pull request merged**
